export type CourseCategory = "Game" | "Skill Badge";
export type SkillLevel = "Beginner" | "Intermediate" | "Advanced";

export interface Course {
  id: string;
  titleKey: string;
  category: CourseCategory;
  url: string;
  courseUrl?: string;
  tags: string[];
  month?: string;
  accessCode?: string;
  badgeImageUrl?: string;
  skillLevel?: SkillLevel;
}

const B = (_id: number): undefined => undefined;

export const COURSES: Course[] = [

  // ══ GAMES — July 2026 ═══════════════════════════════════════════════════
  {
    id: "g-basecamp-jul-2026",
    titleKey: "courses.games.basecamp_jul_2026",
    category: "Game",
    url: "https://www.skills.google/games/7313",
    tags: ["cloud", "fundamentals"],
    month: "Juli",
    accessCode: "1q-basecamp-07511",
    badgeImageUrl: "https://cdn.qwiklabs.com/4U2vlpzq9reboYn5uEz23BcGACB2gzE7LYgjWcLnMj4%3D",
  },
  {
    id: "g-adventure-jul-2026",
    titleKey: "courses.games.adventure_lowcode_jul_2026",
    category: "Game",
    url: "https://www.skills.google/games/7314",
    tags: ["appsheet", "cloud_run", "serverless"],
    month: "Juli",
    accessCode: "1q-lowcode-92316",
    badgeImageUrl: "https://cdn.qwiklabs.com/4fQLKgjIAxTZlNT4DG%2BEmZyldujFT7hY7%2BnCNVSYJGg%3D",
  },
  {
    id: "g-voyage-jul-2026",
    titleKey: "courses.games.voyage_storage_jul_2026",
    category: "Game",
    url: "https://www.skills.google/games/7315",
    tags: ["storage", "data", "security"],
    month: "Juli",
    accessCode: "1q-bucket-58231",
    badgeImageUrl: "https://cdn.qwiklabs.com/uJ%2FftsI%2Bv10gDukvMs1C4f3%2FoylCzKlux7CZmWfiZeU%3D",
  },
  {
    id: "g-trail-jul-2026",
    titleKey: "courses.games.trail_workspace_jul_2026",
    category: "Game",
    url: "https://www.skills.google/games/7316",
    tags: ["workspace", "admin", "security"],
    month: "Juli",
    accessCode: "1q-workspace-31069",
    badgeImageUrl: "https://cdn.qwiklabs.com/7NGqQ0TzcNOq14AvQlqClQuuz61PtIFk0RfLEXYd%2BC0%3D",
  },
  {
    id: "g-safespaces-jul-2026",
    titleKey: "courses.games.safespaces_jul_2026",
    category: "Game",
    url: "https://www.skills.google/games/7318",
    tags: ["security", "gke", "kubernetes"],
    month: "Juli",
    accessCode: "1q-security-19110",
    badgeImageUrl: "https://cdn.qwiklabs.com/wlgUr4hLSfy8uOE7nNMh8rnzMD%2BXoq72kifWCPTWhtw%3D",
  },
  {
    id: "g-simulator-jul-2026",
    titleKey: "courses.games.simulator_datamesh_jul_2026",
    category: "Game",
    url: "https://www.skills.google/games/7317",
    tags: ["data", "bigquery", "dataplex"],
    month: "Juli",
    accessCode: "1q-datamesh-16451",
    badgeImageUrl: "https://cdn.qwiklabs.com/FmH2T828fUAOnuLlIHjzrYPpDescyl%2FLUeVbeHJj%2Ffk%3D",
  },



  // ══ SKILL BADGES — Beginner ══════════════════════════════════════════════
  {
    id: "sb-create-manage-cloud",
    titleKey: "courses.skills.create_manage_cloud",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/648/labs/613025",
    courseUrl: "https://www.skills.google/course_templates/648",
    tags: ["cloud", "infrastructure"],
    skillLevel: "Beginner",
    badgeImageUrl: B(648),
  },
  {
    id: "sb-prepare-data-ml",
    titleKey: "courses.skills.prepare_data_ml",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/631/labs/629218",
    courseUrl: "https://www.skills.google/course_templates/631",
    tags: ["ai", "ml", "data"],
    skillLevel: "Beginner",
    badgeImageUrl: B(631),
  },
  {
    id: "sb-bigquery-connected",
    titleKey: "courses.skills.bigquery_connected",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/632/labs/612199",
    courseUrl: "https://www.skills.google/course_templates/632",
    tags: ["bigquery", "workspace", "data"],
    skillLevel: "Beginner",
    badgeImageUrl: B(632),
  },
  {
    id: "sb-monitor-log",
    titleKey: "courses.skills.monitor_log",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/749/labs/594584",
    courseUrl: "https://www.skills.google/course_templates/749",
    tags: ["monitoring", "logging"],
    skillLevel: "Beginner",
    badgeImageUrl: B(749),
  },
  {
    id: "sb-prompt-design",
    titleKey: "courses.skills.prompt_design",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/976/labs/629198",
    courseUrl: "https://www.skills.google/course_templates/976",
    tags: ["ai", "genai", "gemini"],
    skillLevel: "Beginner",
    badgeImageUrl: B(976),
  },
  {
    id: "sb-develop-genai-streamlit",
    titleKey: "courses.skills.develop_genai_streamlit",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/978/labs/629104",
    courseUrl: "https://www.skills.google/course_templates/978",
    tags: ["ai", "genai", "gemini"],
    skillLevel: "Beginner",
    badgeImageUrl: B(978),
  },
  {
    id: "sb-get-started-cloud-run-functions",
    titleKey: "courses.skills.get_started_cloud_run_functions",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/964",
    courseUrl: "https://www.skills.google/course_templates/964",
    tags: ["serverless", "cloud_run"],
    skillLevel: "Beginner",
    badgeImageUrl: B(964),
  },
  {
    id: "sb-workspace-sheets",
    titleKey: "courses.skills.workspace_sheets",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/769",
    courseUrl: "https://www.skills.google/course_templates/769",
    tags: ["workspace"],
    skillLevel: "Beginner",
    badgeImageUrl: B(769),
  },
  {
    id: "sb-workspace-docs",
    titleKey: "courses.skills.workspace_docs",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/771",
    courseUrl: "https://www.skills.google/course_templates/771",
    tags: ["workspace"],
    skillLevel: "Beginner",
    badgeImageUrl: B(771),
  },
  {
    id: "sb-gemini-workspace",
    titleKey: "courses.skills.gemini_workspace",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/1037",
    courseUrl: "https://www.skills.google/course_templates/1037",
    tags: ["ai", "gemini", "workspace"],
    skillLevel: "Beginner",
    badgeImageUrl: B(1037),
  },
  {
    id: "sb-gke-beginner",
    titleKey: "courses.skills.gke_beginner",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/2",
    courseUrl: "https://www.skills.google/course_templates/2",
    tags: ["kubernetes", "infrastructure"],
    skillLevel: "Beginner",
    badgeImageUrl: B(2),
  },
  {
    id: "sb-cloud-computing-fundamentals",
    titleKey: "courses.skills.cloud_computing_fundamentals",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/153",
    courseUrl: "https://www.skills.google/course_templates/153",
    tags: ["cloud", "fundamentals"],
    skillLevel: "Beginner",
    badgeImageUrl: B(153),
  },
  {
    id: "sb-infra-foundations",
    titleKey: "courses.skills.infra_foundations",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/154",
    courseUrl: "https://www.skills.google/course_templates/154",
    tags: ["cloud", "infrastructure"],
    skillLevel: "Beginner",
    badgeImageUrl: B(154),
  },
  {
    id: "sb-networking-foundations",
    titleKey: "courses.skills.networking_foundations",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/155",
    courseUrl: "https://www.skills.google/course_templates/155",
    tags: ["networking", "security"],
    skillLevel: "Beginner",
    badgeImageUrl: B(155),
  },
  {
    id: "sb-data-ml-foundations",
    titleKey: "courses.skills.data_ml_foundations",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/156",
    courseUrl: "https://www.skills.google/course_templates/156",
    tags: ["data", "ml", "ai"],
    skillLevel: "Beginner",
    badgeImageUrl: B(156),
  },
  {
    id: "sb-app-engine",
    titleKey: "courses.skills.app_engine",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/671",
    courseUrl: "https://www.skills.google/course_templates/671",
    tags: ["app_engine", "serverless"],
    skillLevel: "Beginner",
    badgeImageUrl: B(671),
  },
  {
    id: "sb-manage-google-workspace",
    titleKey: "courses.skills.manage_google_workspace",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/1058",
    courseUrl: "https://www.skills.google/course_templates/1058",
    tags: ["workspace", "cloud"],
    skillLevel: "Beginner",
    badgeImageUrl: B(1058),
  },

  // ══ SKILL BADGES — Intermediate ══════════════════════════════════════════
  {
    id: "sb-bq-analyze",
    titleKey: "courses.skills.bq_analyze",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/761/labs/609037",
    courseUrl: "https://www.skills.google/course_templates/761",
    tags: ["data", "bigquery", "analytics"],
    skillLevel: "Intermediate",
    badgeImageUrl: B(761),
  },
  {
    id: "sb-dataflow",
    titleKey: "courses.skills.dataflow",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/657/labs/613008",
    courseUrl: "https://www.skills.google/course_templates/657",
    tags: ["data", "dataflow"],
    skillLevel: "Intermediate",
    badgeImageUrl: B(657),
  },
  {
    id: "sb-gke",
    titleKey: "courses.skills.gke",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/663/labs/592459",
    courseUrl: "https://www.skills.google/course_templates/663",
    tags: ["infrastructure", "kubernetes"],
    skillLevel: "Intermediate",
    badgeImageUrl: B(663),
  },
  {
    id: "sb-gce",
    titleKey: "courses.skills.gce",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/625/labs/592706",
    courseUrl: "https://www.skills.google/course_templates/625",
    tags: ["infrastructure", "cloud"],
    skillLevel: "Intermediate",
    badgeImageUrl: B(625),
  },
  {
    id: "sb-vpc",
    titleKey: "courses.skills.vpc",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/654/labs/592556",
    courseUrl: "https://www.skills.google/course_templates/654",
    tags: ["networking", "security"],
    skillLevel: "Intermediate",
    badgeImageUrl: B(654),
  },
  {
    id: "sb-security-fund",
    titleKey: "courses.skills.security_fund",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/645/labs/593323",
    courseUrl: "https://www.skills.google/course_templates/645",
    tags: ["security", "iam"],
    skillLevel: "Intermediate",
    badgeImageUrl: B(645),
  },
  {
    id: "sb-cicd",
    titleKey: "courses.skills.cicd",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/691/labs/612999",
    courseUrl: "https://www.skills.google/course_templates/691",
    tags: ["devops", "cicd"],
    skillLevel: "Intermediate",
    badgeImageUrl: B(691),
  },
  {
    id: "sb-cloudsql",
    titleKey: "courses.skills.cloudsql",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/652/labs/613053",
    courseUrl: "https://www.skills.google/course_templates/652",
    tags: ["database", "sql"],
    skillLevel: "Intermediate",
    badgeImageUrl: B(652),
  },
  {
    id: "sb-tf",
    titleKey: "courses.skills.tf",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/636/labs/592700",
    courseUrl: "https://www.skills.google/course_templates/636",
    tags: ["infrastructure", "terraform", "devops"],
    skillLevel: "Intermediate",
    badgeImageUrl: B(636),
  },
  {
    id: "sb-cloudrun",
    titleKey: "courses.skills.cloudrun",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/649/labs/592585",
    courseUrl: "https://www.skills.google/course_templates/649",
    tags: ["serverless", "firebase"],
    skillLevel: "Intermediate",
    badgeImageUrl: B(649),
  },
  {
    id: "sb-looker",
    titleKey: "courses.skills.looker",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/503",
    courseUrl: "https://www.skills.google/course_templates/503",
    tags: ["data", "looker", "analytics"],
    skillLevel: "Intermediate",
    badgeImageUrl: B(503),
  },
  {
    id: "sb-pubsub-streaming",
    titleKey: "courses.skills.pubsub_streaming",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/752/labs/598649",
    courseUrl: "https://www.skills.google/course_templates/752",
    tags: ["data", "bigquery", "streaming"],
    skillLevel: "Intermediate",
    badgeImageUrl: B(752),
  },
  {
    id: "sb-networking-fundamentals-intermediate",
    titleKey: "courses.skills.networking_fundamentals_intermediate",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/748/labs/461543",
    courseUrl: "https://www.skills.google/course_templates/748",
    tags: ["networking"],
    skillLevel: "Intermediate",
    badgeImageUrl: B(748),
  },
  {
    id: "sb-bq-ml",
    titleKey: "courses.skills.bq_ml",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/23",
    courseUrl: "https://www.skills.google/course_templates/23",
    tags: ["data", "bigquery", "ml"],
    skillLevel: "Intermediate",
    badgeImageUrl: B(23),
  },
  {
    id: "sb-dataplex",
    titleKey: "courses.skills.dataplex",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/660",
    courseUrl: "https://www.skills.google/course_templates/660",
    tags: ["data", "analytics"],
    skillLevel: "Intermediate",
    badgeImageUrl: B(660),
  },
  {
    id: "sb-cloudrun2",
    titleKey: "courses.skills.cloudrun2",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/637/labs/592550",
    courseUrl: "https://www.skills.google/course_templates/637",
    tags: ["infrastructure", "cloud"],
    skillLevel: "Intermediate",
    badgeImageUrl: B(637),
  },
  {
    id: "sb-workspace-sec",
    titleKey: "courses.skills.workspace_sec",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/676/labs/625105",
    courseUrl: "https://www.skills.google/course_templates/676",
    tags: ["security", "workspace"],
    skillLevel: "Intermediate",
    badgeImageUrl: B(676),
  },

  // ══ SKILL BADGES — Advanced ══════════════════════════════════════════════
  {
    id: "sb-vertex-mlops",
    titleKey: "courses.skills.vertex_mlops",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/684",
    courseUrl: "https://www.skills.google/course_templates/684",
    tags: ["ai", "ml", "vertex_ai"],
    skillLevel: "Advanced",
    badgeImageUrl: B(684),
  },
  {
    id: "sb-vector-search",
    titleKey: "courses.skills.vector_search",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/1133",
    courseUrl: "https://www.skills.google/course_templates/1133",
    tags: ["ai", "genai", "vertex_ai"],
    skillLevel: "Advanced",
    badgeImageUrl: B(1133),
  },
  {
    id: "sb-responsible-ai",
    titleKey: "courses.skills.responsible_ai",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/388",
    courseUrl: "https://www.skills.google/course_templates/388",
    tags: ["ai", "ml"],
    skillLevel: "Advanced",
    badgeImageUrl: B(388),
  },
  {
    id: "sb-monitor",
    titleKey: "courses.skills.monitor",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/653",
    courseUrl: "https://www.skills.google/course_templates/653",
    tags: ["infrastructure", "monitoring"],
    skillLevel: "Advanced",
    badgeImageUrl: B(653),
  },
  {
    id: "sb-devops-sre",
    titleKey: "courses.skills.devops_sre",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/919",
    courseUrl: "https://www.skills.google/course_templates/919",
    tags: ["devops", "serverless", "cloud_run"],
    skillLevel: "Advanced",
    badgeImageUrl: B(919),
  },
  {
    id: "sb-alloydb",
    titleKey: "courses.skills.alloydb",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/642/labs/612109",
    courseUrl: "https://www.skills.google/course_templates/642",
    tags: ["database"],
    skillLevel: "Advanced",
    badgeImageUrl: B(642),
  },
  {
    id: "sb-bigtable",
    titleKey: "courses.skills.bigtable",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/650/labs/607133",
    courseUrl: "https://www.skills.google/course_templates/650",
    tags: ["database"],
    skillLevel: "Advanced",
    badgeImageUrl: B(650),
  },
  {
    id: "sb-gemini-dev",
    titleKey: "courses.skills.gemini_dev",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/982",
    courseUrl: "https://www.skills.google/course_templates/982",
    tags: ["ai", "gemini"],
    skillLevel: "Advanced",
    badgeImageUrl: B(982),
  },
  {
    id: "sb-vertex-ai-studio",
    titleKey: "courses.skills.vertex_ai_studio",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/1001",
    courseUrl: "https://www.skills.google/course_templates/1001",
    tags: ["ai", "vertex_ai", "genai"],
    skillLevel: "Advanced",
    badgeImageUrl: B(1001),
  },
  {
    id: "sb-gemini-multimodal",
    titleKey: "courses.skills.gemini_multimodal",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/981",
    courseUrl: "https://www.skills.google/course_templates/981",
    tags: ["ai", "gemini", "genai"],
    skillLevel: "Advanced",
    badgeImageUrl: B(981),
  },
  {
    id: "sb-gemini-api-app",
    titleKey: "courses.skills.gemini_api_app",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/1083",
    courseUrl: "https://www.skills.google/course_templates/1083",
    tags: ["ai", "genai", "gemini"],
    skillLevel: "Advanced",
    badgeImageUrl: B(1083),
  },
  {
    id: "sb-firebase-pipeline",
    titleKey: "courses.skills.firebase_pipeline",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/989",
    courseUrl: "https://www.skills.google/course_templates/989",
    tags: ["devops", "firebase", "cicd"],
    skillLevel: "Advanced",
    badgeImageUrl: B(989),
  },
  {
    id: "sb-gke-costs",
    titleKey: "courses.skills.gke_costs",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/655/labs/598645",
    courseUrl: "https://www.skills.google/course_templates/655",
    tags: ["kubernetes", "infrastructure"],
    skillLevel: "Advanced",
    badgeImageUrl: B(655),
  },
  {
    id: "sb-engineer-ai-agents",
    titleKey: "courses.skills.engineer_ai_agents",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/1598",
    courseUrl: "https://www.skills.google/course_templates/1598",
    tags: ["ai", "gemini", "genai"],
    skillLevel: "Advanced",
    badgeImageUrl: B(1598),
  },
  {
    id: "sb-gemini-for-devs",
    titleKey: "courses.skills.gemini_for_devs",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/1209",
    courseUrl: "https://www.skills.google/course_templates/1209",
    tags: ["ai", "gemini", "devops"],
    skillLevel: "Advanced",
    badgeImageUrl: B(1209),
  },
  {
    id: "sb-cloud-run-advanced",
    titleKey: "courses.skills.cloud_run_advanced",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/741",
    courseUrl: "https://www.skills.google/course_templates/741",
    tags: ["serverless", "cloud_run"],
    skillLevel: "Advanced",
    badgeImageUrl: B(741),
  },
  {
    id: "sb-workspace-admin",
    titleKey: "courses.skills.workspace_admin",
    category: "Skill Badge",
    url: "https://www.skills.google/course_templates/676/labs/625105",
    courseUrl: "https://www.skills.google/course_templates/676",
    tags: ["workspace", "security"],
    skillLevel: "Advanced",
    badgeImageUrl: B(676),
  },
];

// ── Derived exports ────────────────────────────────────────────────────────
export const ALL_TAGS = Array.from(
  new Set(COURSES.flatMap((c) => c.tags))
).sort();

export const ALL_MONTHS = ["Juli"];

export function getActiveMonth(): string {
  const m = new Date().getMonth() + 1;
  if (m === 7) return "Juli";
  if (m === 8) return "Agustus";
  if (m === 9) return "September";
  return "Juli";
}
